### ISSUE TITLE
Where should (go)sam3 development continue?

### ISSUE THREAD

**Issue by hkh4n** [eyedeekay/sam3#9]
From what I see, most development has been done on this fork here. But since things have moved to the go-i2p group, should resumed development be on https://github.com/go-i2p/sam3 instead of https://github.com/eyedeekay/sam3/ ?

Thanks!

**Comment by eyedeekay** [comment]
Until I change the module path, let's keep development here. Changing the module path is kind of unpleasant so let's wait on that for a while and do it in a couple weeks.

**Comment by eyedeekay** [comment]
All right it's after release, so time to revisit this. go/sam3 isn't exactly housed in just one place anymore, there are 4 libraries to migrate into `go-i2p`, from bottom to top in terms of dependencies:

1. `i2pkeys`
2. `sam3`
3. `gosam`
4. `onramp`

We want to figure out how to move all four of these to the `go-i2p` org namespace in the least disruptive way possible. I think we can do this without breaking anybody's builds by updating just updating the module paths and creating new releases after that point. Old versions will continue to use the old module path, if I understand correctly. We do this by doing `go mod edit -module github.com/go-i2p/$REPO`, and creating a new tag. I'll make sure it works this way and move on in the next week.

**Comment by eyedeekay** [comment]
Module paths were officially changed last week and added to the go-i2p organizational onboarding document. Closing this here.
